version: '3.9'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: petroz
      POSTGRES_PASSWORD: petroz
      POSTGRES_DB: petroz
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - '8080:80'
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./symfony:/var/www/html
    depends_on:
      - php-fpm
  php-fpm:
    build:
      context: .
      dockerfile: Dockerfile.php-fpm
    depends_on:
      - postgres
    volumes:
      - ./symfony:/var/www/html
      - /var/log/fpm-php.www.log:/var/log/fpm-php.www.log
    command: >
      sh -c "composer create-project symfony/skeleton:\"6.3.*\" . &&
             composer require symfony/monolog-bundle &&
             composer require symfony/form &&
             composer require symfony/orm-pack &&
             composer require --dev symfony/maker-bundle &&
             composer require symfony/serializer
             composer require symfony/validator
             php-fpm"

volumes:
  postgres-data:
