FROM nginx:latest

# Копируем конфигурацию Nginx в контейнер
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Папка для статических файлов Symfony
WORKDIR /var/www/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]

